apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-click-housh-zookeeper-0
  #namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-click-housh-zookeeper-0"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: default
    name: data-click-housh-zookeeper-0
